// Public surface of the platform module - cross-module imports go through here.
export { PlatformModule } from './platform.module'
export { PrismaService } from './prisma.service'
export { ControlPlaneAuditService } from './audit.service'
export type { ControlPlaneAuditEntry } from './audit.service'
export { MANAGER_GATED_ACTIONS, ManagerAuthService } from './manager-auth.service'
export type { ManagerApproval, ManagerGatedAction, ManagerGatedActor } from './manager-auth.service'
export { CurrentOperator, Public } from './ops-auth.guard'
export { CurrentOwner } from './admin-auth.guard'
export { RegionRegistryService } from './region-registry.service'
export { uuidv7 } from './uuidv7'
export { OPS_SESSION_TTL_SECONDS, signOpsToken } from './ops-jwt'
export type { OpsPrincipal } from './ops-jwt'
export { ADMIN_SESSION_TTL_SECONDS, signAdminToken } from './admin-jwt'
export type { AdminPrincipal } from './admin-jwt'
