// Public surface of the platform module - cross-module imports go through here.
export { PlatformModule } from './platform.module'
export { PrismaService } from './prisma.service'
export { ControlPlaneAuditService } from './audit.service'
export type { ControlPlaneAuditEntry } from './audit.service'
export { MANAGER_GATED_ACTIONS, ManagerAuthService } from './manager-auth.service'
export type { ManagerApproval, ManagerGatedAction, ManagerGatedActor } from './manager-auth.service'
export { CurrentOperator, IS_PUBLIC, Public } from './ops-auth.guard'
export { CurrentOwner } from './admin-auth.guard'
export { CurrentStaff } from './pos-auth.guard'
export { CurrentGuest } from './guest-auth.guard'
export { CurrentDevice } from './device-sync.guard'
export type { DevicePrincipal } from './device-sync.guard'
export { parseEd25519PublicKey, signingString } from './device-signature'
export { RegionRegistryService } from './region-registry.service'
export { AttemptLimiter } from './attempt-limiter'
export { ClientIp } from './client-ip'
export type { AttemptRule } from './attempt-limiter'
export { uuidv7 } from './uuidv7'
export { paymentsSimulatorEnabled } from './payments-simulator'
export { OPS_SESSION_TTL_SECONDS, signOpsToken } from './ops-jwt'
export type { OpsPrincipal } from './ops-jwt'
export { ADMIN_SESSION_TTL_SECONDS, signAdminToken } from './admin-jwt'
export type { AdminPrincipal } from './admin-jwt'
export { POS_SESSION_TTL_SECONDS, POS_PENDING_TTL_SECONDS, signPosToken, signPosPendingToken, verifyPosPendingToken } from './pos-jwt'
export type { PosPrincipal, PosPendingPrincipal, PosTokenClaims } from './pos-jwt'
export { AnyStaff, PERMISSIONS, permissionsFor, RequirePermission, ROLE_PERMISSIONS, ROUTE_PERMISSION, roleHasPermission } from './permissions'
export type { Permission } from './permissions'
export { GUEST_SESSION_TTL_SECONDS, signGuestToken } from './guest-jwt'
export type { GuestPrincipal } from './guest-jwt'
export { assertProductionConfig } from './production-config'
export { reserveTokenNumber } from './token-number'
export { MailService } from './mail.service'
export type { MailMessage } from './mail.service'
export { baseDomain, TENANT_HOST_HEADER, TenantAddressService } from './tenant-address.service'
export { RESERVED_SLUGS, SLUG_PATTERN, slugFromHost, slugify, slugProblem } from './tenant-slug'
export type { SlugProblem } from './tenant-slug'
